#!/bin/bash
# version: 3.0
# For use with the direct camera RS232 connection without additional control board 
#
# require root privilege
# usage: sudo ./ptz-server <start | stop >
#
# 1. Read `vars` file inside $scriptBin (inside /usr/local/ipcam/bin)
# 2. Set Visca serial port to what was found in the above step
# 3. Stop the `ttyVisca` normally in use for system console 
# 4. Start the `server.py` to listen `listePort` and use the Visca serial port `ttyVisca`

scriptDir="/usr/local/ipcam"
scriptBin=$scriptDir/bin
tempDir=$scriptDir/tmp
varsFile=$scriptBin/vars
pidFile="$tempDir/run-ptzserver.pid"

listenPort=3789
ttyVisca=`grep ttyVisca $varsFile | awk -F'=' '{print $2}'`
tty=`echo $ttyVisca | awk -F '/' '{print $3}'`

close_console() {
	serialStatus=`/sbin/status $tty | awk '{print $2}' | grep start | wc -l`
	if [ $serialStatus -gt 0 ]; then
		/sbin/stop $tty
	fi
}

start_console() {
	serialStatus=`/sbin/status $tty | awk '{print $2}' | grep stop | wc -l`
	if [ $serialStatus -gt 0 ]; then
		/sbin/start $tty
	fi
}

ptzsrv_up() {
	# check existing server.py whether it is already running
	srvStatus=`ps -ef | grep server.py | grep -v grep | awk '{print $2}'`

	if [ "$srvStatus" != ""  ]; then
		echo "[server.py]: server.py is already running at PID $srvStatus"
	else
		# start a new server.py
		if [ -f $pidFile ]; then
			rm $pidFile
		fi	
		$scriptBin/server.py $listenPort $ttyVisca &
		echo $! > $pidFile
		echo "[server.py]: server.py is started"
	fi
}

ptzsrv_down() {
	if [ ! -f $pidFile ]; then
		pkill server.py
	else
		kill -9 `cat $pidFile`
	fi	
}	

case "$1" in
 
start)
	close_console
	ptzsrv_up
	;;
stop)
	start_console
	ptzsrv_down
	;;
*)
	echo "Usage: $0 {start|stop}"
	;;
esac
exit 0
